### ISSUE TITLE
LTO version mismatch during build on [Ubuntu]

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1740] opened 2015-01-08 19:35 UTC
See [original report](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-January/010107.html). 

![image 1](https://cloud.githubusercontent.com/assets/15566/5669137/244afbc0-972a-11e4-8162-202ec1502a0e.png)

@breznak Do you recognize that LTO version problem? I found this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62083

**Comment by breznak** [comment] 2015-01-08 19:47
@rhyolight yes, 
this looks like a dupe of #1698  (you are using gcc-4.9, right?) 

they can `export NUPIC_DEPLOYMENT_BUILD=true` in nupic, resp. nupic.core to take LTO out of the game, but if it's the 4.9 compiler, it's the #1699 and nupic won't build at all.

**Comment by rhyolight** [comment] 2015-01-08 19:57
@breznak He [says he's using gcc 4.7.2](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-January/010110.html)...

**Comment by breznak** [comment] 2015-01-08 20:03
same problem in #1699 - binary build of nupic.core from Travis will not link (LTO or not). 
he can compile himself, that will do 
nupic.core: `cmake ../../src -DCMAKE_INSTALL_PREFIX=../release && make -j4 && make install && make tests_all`

nupic: `python setup.py build --cmake_options="-DNUPIC_CORE=/your/path/nupic.core/build/release"`

**Comment by tsenggordon** [comment] 2015-01-11 18:23
Dear all:

    When I built nupic first time, it failed in the midway. Because I was not sure that I can clean the wreckages, I removed the VM and made sure all building procedure working properly. Then, the error didn't show up again, so I guess this error is caused by incomplete make install procedure.

**Comment by tsenggordon** [comment] 2015-01-11 18:23
Dear all:
When I built nupic first time, it failed in the midway. Because I was not sure that I can clean the wreckages, I removed the VM and made sure all building procedure working properly. Then, the error didn't show up again, so I guess this error is caused by incomplete make install procedure.

**Comment by breznak** [comment] 2015-01-12 11:58
@tsenggordon hi, thank you for the update! glad it's working for you :+1:  
PS: next time `git clean -xdf` should be enough to reset to "factory defaults"

**Closed** 2015-02-25 05:17 UTC
Labels: bug, build failure, P3
