### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by alxkls** [numenta/nupic#2102] opened 2015-05-04 10:44 UTC
Hello everyone, 

I am having problems compiling the package. I get the following error:
`nupic lto1: fatal error: bytecode stream generated with LTO version 2.2 instead of the expected 3.0`

I found someone had similar issue and the solution he proposed was to downgrade gcc and g++. Sadly I can't do that as it will brake many other things. Does anyone have any other suggestions. Thanks.

**Comment by rhyolight** [comment] 2015-05-04 14:14
Can you give some details about your environment?
- python version
- compiler (type and version)
- operating system and bitness

**Comment by rhyolight** [comment] 2015-05-04 14:15
This is probably a duplicate of https://github.com/numenta/nupic/issues/1699, but asking for further details before making an assumption.

**Comment by alxkls** [comment] 2015-05-04 19:12
Error:
` #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/alex/dev/python/packages/nupic/external/linux64/include -I/home/alex/dev/python/packages/nupic/external/common/include -I/home/alex/dev/python/packages/nupic/extensions -I/home/alex/dev/python/packages/nupic -I/home/alex/dev/python/packages/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c extensions/cpp_region/unittests/PyHelpersTest.cpp -o build/temp.linux-x86_64-2.7/extensions/cpp_region/unittests/PyHelpersTest.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
g++ -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/extensions/py_support/NumpyVector.o build/temp.linux-x86_64-2.7/extensions/py_support/PyArray.o build/temp.linux-x86_64-2.7/extensions/py_support/PyHelpers.o build/temp.linux-x86_64-2.7/extensions/py_support/PythonStream.o build/temp.linux-x86_64-2.7/extensions/cpp_region/PyRegion.o build/temp.linux-x86_64-2.7/extensions/cpp_region/unittests/PyHelpersTest.o /home/alex/dev/python/packages/nupic/extensions/core/build/release/lib/libnupic_core.a -L. -ldl -lpython2.7 -lkj -lcapnp -lcapnpc -lpthread -lpython2.7 -o build/lib.linux-x86_64-2.7/nupic/libcpp_region.so -m64 -fPIC -L/home/alex/dev/python/packages/nupic/extensions/core/build/release/lib -lkj -lcapnp -lcapnpc -O2
lto1: fatal error: bytecode stream generated with LTO version 2.2 instead of the expected 3.0
compilation terminated.
lto-wrapper: g++ returned 1 exit status
/bin/ld: lto-wrapper failed
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
`

Python
`Python 2.7.8 (default, Nov 10 2014, 08:19:18) `

GCC/G++
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20141101/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20141101/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20141101 (Red Hat 4.9.2-1) (GCC) ```

OS: Fedora 21 and Arch 2015.04.01(same error on both). I should mention that it worked fine on my servers(CentOS 7.1).

Bitness:  `x86_64`

**Comment by rhyolight** [comment] 2015-05-05 19:26
@alxkls We currently have compatibility problems with GCC 4.9 because of LTO, so this looks like a duplicate of #1699. The only work-around is to install GCC 4.8. Sorry.

**Closed by rhyolight** 2015-05-05 19:26 UTC
Labels: type:bug, type:installation
