### ISSUE TITLE
Investigate possible optimization in TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#903] opened 2014-05-01 02:20 UTC
In `inferPhase2`, we have logic that checks if a segment "has the min number of active synapses" before computing whether the segment is active. Is this an optimization, or necessary for correct function?

This task is to determine the answer to that question, and accordingly update the comment.

**Comment by rhyolight** [comment] 2016-07-20 18:26
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Closed** 2016-07-20 18:31 UTC
Labels: subject:algorithms, under-review
