### ISSUE TITLE
Problem Installing NuPIC on Linux - No module named math

### ISSUE THREAD

**Issue by jburman789** [numenta/nupic#2085] opened 2015-04-27 15:37 UTC
I am new to NuPIC and I have downloaded and installed the software from GitHub. However, when I attempt to run the examples, I continually get the ImportError: No module named math. The math module is imported in several examples and when I enter python, I can import math. How can I correct the error I am receiving when trying the NuPIC examples? Thanks in advance,

python hierarchy_network_demo.py
Traceback (most recent call last):
File "hierarchy_network_demo.py", line 38, in 
from nupic.algorithms.anomaly import computeRawAnomalyScore
File "/home/jerry/MATLAB/R2014b/bin/NuPic/nupic/algorithms/init.py", line 28, in 
from nupic.bindings.math import NearestNeighbor
ImportError: No module named math

**Comment by rhyolight** [comment] 2015-04-27 16:13
Duplicate of #2086.

**Closed by rhyolight** 2015-04-27 16:13 UTC
Labels: duplicate
