### ISSUE TITLE
Remove unused methods in Encoders

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#572] opened 2014-01-17 22:52 UTC
There are a number of methods in the Encoder base class that are difficult to implement but unused. We should remove them. This will make it simpler for people to understand and implement encoders.  The methods should be listed and then someone could remove them. To validate the changes we should run swarms, hotgym, etc.

**Comment by breznak** [comment] 2015-02-23 06:46
@subutai is this still valid? Can you point to candidate methods for removal? I'd like to finish #1355 and start writing C++ some encoders

**Comment by breznak** [comment] 2015-02-23 06:46
ref #1479

**Comment by subutai** [comment] 2015-02-24 16:36
I think it might still be valid. Some possible examples are closenessScores(), topDownCompute(), decode(). Not sure these methods are actually used anymore.

**Comment by breznak** [comment] 2015-02-24 16:42
:+1: I will check, I believe those functions are used only in tests, not in practice. That would simplify the porting or changes a lot. 

On the other hand, I always wanted to bring top-down flow (reconstruction) back to life in nupic :game_die: @rhyolight can you make me a git tag "before_reconstruction_removal" or something, so I have a reference for future? Then I will be happy to prune these methods!

**Comment by breznak** [comment] 2015-03-03 18:03
hmm, I actually cry when removing the `decode() topDownCompute()` code :) , so I don't really wanna do it. But I want to lower the bar for C++ encoders as much as possible. Could I instead just mark methods in `base` as required (`encode() init()` and all their requirements) for the c++ implementation and leave rest optional?

**Comment by rhyolight** [comment] 2015-03-03 21:50
> can you make me a git tag "before_reconstruction_removal" or something

Done

**Comment by rhyolight** [comment] 2016-07-14 16:23
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

**Closed** 2018-06-25 19:19 UTC
Labels: priority:4, subject:encoders, type:cleanup, under-review
