### ISSUE TITLE
Allow PAM to be disabled in TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#982] opened 2014-06-03 20:38 UTC
The current TP implementation doesn't allow for disabling PAM by setting `pamLength` to 0 (even though the docstring says it does).

**Comment by rhyolight** [comment] 2016-07-20 18:35
### Please review this issue

### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Comment by subutai** [comment] 2016-07-21 22:50
Obsolete - old TP code.

**Closed** 2016-07-22 00:48 UTC
Labels: priority:4, subject:algorithms, type:docs, under-review
