### ISSUE TITLE
If possible, remove confidences calculation from TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#907] opened 2014-05-02 06:21 UTC
According to @subutai, the CLA Classifier has taken on the role of producing probability / confidence measures of predictions, so we probably can remove that computation from the TP.

**Comment by rhyolight** [comment] 2016-07-20 18:26
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Comment by subutai** [comment] 2016-07-20 20:38
> Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

Agreed - obsolete.

**Closed** 2016-07-20 21:16 UTC
Labels: subject:algorithms, under-review
