### ISSUE TITLE
with out-of-bounds index 29, but container only holds 29 elements.

### ISSUE THREAD

**Issue by chrisbangun** [numenta/nupic#3372] opened 2016-10-07 02:39 UTC
> **NOTE**: Tracking internally at https://jira.numenta.com/browse/NUP-2324

hey guys,

I tried to  [Install NuPIC using Docker](https://github.com/numenta/nupic/wiki/Install-NuPIC-using-Docker). However, I got an error  when running this command:
`docker run -i -t numenta/nupic /bin/bash -c "python /usr/local/src/nupic/examples/opf/clients/hotgym/simple/hotgym.py"`
and this:
`docker run -i -t numenta/nupic /bin/bash -c "python /usr/local/src/nupic/scripts/run_opf_experiment.py /usr/local/src/nupic/examples/opf/experiments/multistep/hotgym/"
`
The following is the error that I got:

```
usr/include/c++/4.8/debug/vector:346:error: attempt to subscript container 
    with out-of-bounds index 29, but container only holds 29 elements.

Objects involved in the operation:
sequence "this" @ 0x0x4857040 {
  type = NSt7__debug6vectorIN5nupic10algorithms6Cells49InSynapseESaIS4_EEE;
}
```

any advise would be really appreciated. Thanks

**Comment by rhyolight** [comment] 2016-10-07 15:00
@allanino @oxtopus Can one of you investigate sometime?

**Comment by metinhavaci** [comment] 2017-01-25 11:58
I got a very similar error when I built nupic.core 0.5.0 in debug mode and run ```src/nupic/examples/opf/clients/hotgym/simple/hotgym.py```.

In my case the error is:
```
/usr/include/c++/5/debug/vector:409:error: attempt to subscript container 
    with out-of-bounds index 27, but container only holds 27 elements.

Objects involved in the operation:
sequence "this" @ 0x0x50c7010 {
  type = NSt7__debug6vectorIN5nupic10algorithms6Cells49InSynapseESaIS4_EEE;
}
```
 I repeated the same thing with using nupic.core 0.4.0 (built in debug mode, installed with setup.py develop) and nupic 0.5.0 (installed with setup.py develop) and I got no error. But when I added below code snipped after line 373 of file ```src/nupic/algorithms/Segment.cpp``` and recompiled nupic.core 0.4.0, I saw lots of error messages.

```
if (_synapses.size() <= inactiveSegmentIndices[i])
          {
                  std::cout << "!!! there is a problem !!! _synapses.size: " << _synapses.size();
                  std::cout << " inactiveSegmentIndices[i]:" << inactiveSegmentIndices[i] <<" i :" << i << " \n";
          }

```

Error messages:
```
!!! there is a problem !!! _synapses.size: 26 inactiveSegmentIndices[i]:26 i :14 
!!! there is a problem !!! _synapses.size: 26 inactiveSegmentIndices[i]:27 i :15 
!!! there is a problem !!! _synapses.size: 26 inactiveSegmentIndices[i]:28 i :16 
!!! there is a problem !!! _synapses.size: 29 inactiveSegmentIndices[i]:30 i :15 
!!! there is a problem !!! _synapses.size: 25 inactiveSegmentIndices[i]:26 i :14 
!!! there is a problem !!! _synapses.size: 25 inactiveSegmentIndices[i]:27 i :15 
!!! there is a problem !!! _synapses.size: 32 inactiveSegmentIndices[i]:32 i :17 
!!! there is a problem !!! _synapses.size: 31 inactiveSegmentIndices[i]:32 i :14 
INFO:__main__:After 100 records, 1-step altMAPE=38.390240
!!! there is a problem !!! _synapses.size: 29 inactiveSegmentIndices[i]:29 i :15 
!!! there is a problem !!! _synapses.size: 29 inactiveSegmentIndices[i]:30 i :16
...
```

I don't know HTM theory very well, but I believe that the cause of problem is invalid index numbers in the vector ```inactiveSegmentIndices```.  There may be other vectors which contain invalid index numbers. (probably ```activeSegmentIndices```)

In function ```Cells4::adaptSegment``` (file:Cells4.cpp) at line 1656
```
    segment.updateSynapses(synToDec, - _permDec, _permMax, _permConnected, removed);
```
The above line can cause remove of some elements from vector ```_synapses```. In this case the index numbers in```inactiveSegmentIndices``` may become invalid. 

For example ```_synapses``` may hold 10 elements and ```inactiveSegmentIndices``` may  hold values ```[0,1,2,7,8]```. At line 1656 of Cells4.cpp permanence of some elements may decrease below 0 and they can be removed from vector ```_synapses```. Lets say first 3 elements are removed. So trying to access ```_synapses[8]``` can break the program since it has only 7 elements at Segment::freeNSynapses. In this case  I believe that the correct values of```inactiveSegmentIndices``` are ```[4,5]``` but since it was not updated after line 1656 of Cells4.cpp it still contains same values ```[0,1,2,7,8]``` which are invalid.

**Comment by rhyolight** [comment] 2017-01-25 15:27
@metinhavaci Thanks for the info. Can you tell me what OS you are running and also what method you used to install NuPIC? You are not running in Docker, right?

**Comment by metinhavaci** [comment] 2017-01-26 11:19
Yes, I am not running in Docker. I compiled from source codes as described in readme.md
nupic.core 0.5.0 : Linux Mint 18
nupic.core 0.4.0 : Ubuntu 14.04

**Comment by rhyolight** [comment] 2017-01-26 15:10
You tried different nupic version on different OSes?

**Comment by metinhavaci** [comment] 2017-01-27 05:51
Yes. 
I got error messages when I tried to build nupic.core 0.4.0 with gcc 5.4.0. Since version of gcc in default repositories on Ubuntu 14.04 is 4.8, I used Ubuntu 14.04.

**Comment by metinhavaci** [comment] 2017-02-02 06:23
I think this error is releated with https://github.com/numenta/nupic.core/issues/1014

**Comment by breznak** [comment] 2017-02-07 22:29
I hit the same error in the official `numenta/nupic Docker image` with recent nupic (0.5.8.dev0). 

```
root@0b43ad265ced:/usr/local/src/nupic# python scripts/run_opf_experiment.py examples/opf/experiments/anomaly/temporal/hotgym/
Using logging configuration file: /usr/local/lib/python2.7/dist-packages/nupic-0.5.8.dev0-py2.7.egg/nupic/support/nupic-logging.conf
2017-02-07 22:25:39,513 - com.numenta.nupic.data.StreamReader(54) - INFO - StreamReader: Saving generated records to: '/tmp/tmpRF7rh7/generated_output.csv'
OPENING OUTPUT FOR PREDICTION WRITER AT: '/usr/local/src/nupic/examples/opf/experiments/anomaly/temporal/hotgym/inference/DefaultTask.TemporalAnomaly.predictionLog.csv'
Prediction field-meta: [('reset', 'int', 'R'), ('address', 'string', ''), ('consumption', 'string', ''), ('gym', 'string', ''), ('timestamp', 'string', ''), ('multiStepPredictions.actual', 'string', ''), ('multiStepPredictions.1', 'string', ''), ('multiStepPredictions.5', 'string', ''), ('multiStepBucketLikelihoods.1', 'string', ''), ('multiStepBucketLikelihoods.5', 'string', ''), ('multiStepBestPredictions.actual', 'string', ''), ('multiStepBestPredictions.1', 'string', ''), ('multiStepBestPredictions.5', 'string', ''), ('anomalyScore', 'string', ''), ('anomalyLabel', 'string', ''), ("multiStepBestPredictions:multiStep:errorMetric='aae':steps=1:window=1000:field=consumption", 'float', ''), ("prediction:trivial:errorMetric='aae':steps=5:window=1000:field=consumption", 'float', ''), ("multiStepBestPredictions:multiStep:errorMetric='aae':steps=5:window=1000:field=consumption", 'float', ''), ("prediction:trivial:errorMetric='aae':steps=1:window=1000:field=consumption", 'float', '')]
/usr/include/c++/4.8/debug/vector:346:error: attempt to subscript container
    with out-of-bounds index 31, but container only holds 30 elements.

Objects involved in the operation:
sequence "this" @ 0x0x1c1b7b0 {
  type = NSt7__debug6vectorIN5nupic10algorithms6Cells49InSynapseESaIS4_EEE;
}
Aborted (core dumped)
```

Interestingly, this happens only in the hotgym dataset, simple works fine. 

PS: tried to get the core dump (ulimit -c unlimited), but nothing is created. The "root" in docker may be weird, doesnt let me run dmesg, for example...

**Comment by vitaly-krugl** [comment] 2017-02-27 01:09
Duplicate of https://github.com/numenta/nupic.core/issues/1014

**Closed by vitaly-krugl** 2017-02-27 01:09 UTC
Labels: priority:3, triage, type:bug, type:build
