### ISSUE TITLE
Rename python files to follow python convention names (snake_case)

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#971] opened 2014-06-02 13:29 UTC
`snake_case` is the default for python projects, but there're some names in non-compliance to this convention (files in `/nupic`, `/examples`, and `/tests` folders). Examples:

Using UpperCamelCase:
`nupic / nupic / algorithms / CLAClassifier.py`
`nupic / nupic / research / TrivialPredictor.py`

Missing `_` for separate words:
`nupic / nupic / data / functionsource.py`
`nupic / nupic / data / datasethelpers.py`

Unknow achronyms:
`nupic / nupic / data / MCMC.py`

These and other files names should be fixed to `snake_case` convention and if possible use more descriptive names.

**Comment by rhyolight** [comment] 2016-07-20 18:31
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

**Closed** 2018-06-25 19:19 UTC
Labels: priority:4, type:cleanup, under-review
