### ISSUE TITLE
Resumable swarming

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1341] opened 2014-09-18 22:43 UTC
The swarming process is costly - long and consumes lot of CPU. Make sure the work is never lost.

- [ ] always save best model - so that (un)intentional kill leaves me with best-se-far parameters in `model_0/`
- [ ] store the state of searching algorithm somewhere,  so it can resume from where it left off

**Comment by rhyolight** [comment] 2015-03-18 12:55
Duplicate of #758 & #1714.

**Closed by rhyolight** 2015-03-18 12:55 UTC
Labels: enhancement, swarming

**Comment by cogmission** [comment] 2015-03-18 12:57
Ok, but which one is the canonical issue?

On Wed, Mar 18, 2015 at 7:55 AM, Matthew Taylor <notifications@github.com>
wrote:

> Duplicate of #758 <https://github.com/numenta/nupic/issues/758> & #1714
> <https://github.com/numenta/nupic/issues/1714>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/1341#issuecomment-82956829>.
>



-- 
Mit freundlichen Grüßen,
*With kind regards,*

David Ray
Java Solutions Architect
*cortical.io <http://cortical.io> GmbH*
sponsor of:  HTM.java (open source) <https://github.com/numenta/htm.java>
Mariahilferstrasse 4, 1070 Vienna, Austria
d.ray@cortical.io
http://cortical.io

**Comment by rhyolight** [comment] 2015-03-18 13:10
https://github.com/numenta/nupic/issues/1941 is the super issue.

**Comment by cogmission** [comment] 2015-03-18 13:14
Cool, I have my eye on this one!

On Wed, Mar 18, 2015 at 8:10 AM, Matthew Taylor <notifications@github.com>
wrote:

> #1941 <https://github.com/numenta/nupic/issues/1941> is the super issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/1341#issuecomment-82963363>.
>



-- 
Mit freundlichen Grüßen,
*With kind regards,*

David Ray
Java Solutions Architect
*cortical.io <http://cortical.io> GmbH*
sponsor of:  HTM.java (open source) <https://github.com/numenta/htm.java>
Mariahilferstrasse 4, 1070 Vienna, Austria
d.ray@cortical.io
http://cortical.io
