### ISSUE TITLE
Linux Install Issue with PIP 

### ISSUE THREAD

**Issue by eebeer** [numenta/nupic#1983] opened 2015-04-02 17:10 UTC
In RHEL 6,

I installed all dependencies then tried to install nupic via pip, but failed with those errors.

Do you know how can I fix it?

[dkim451@ece ~]$ pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl --user
Downloading/unpacking https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
  Downloading nupic-0.2.1-cp27-none-linux_x86_64.whl (22.6Mb): 22.6Mb downloaded
  Running setup.py egg_info for package from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-4mnzsw-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-4mnzsw-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /nv/hp20/dkim451/.pip/pip.log

**Comment by breznak** [comment] 2015-04-02 17:13
hi,

does the file  '/tmp/pip-4mnzsw-build/setup.py' exist?
Also, you may check execute permissions of /tmp (some systems have /tmp
mounted with 'noexec', see $mount )

Cheers, Mark

**Comment by eebeer** [comment] 2015-04-02 17:20
drwx------   6 dkim451        ece 4.0K Apr  2 11:27 pip-4mnzsw-build

yes I have permission to execute/write, but there is no setup.py under this directory.

**Comment by rhyolight** [comment] 2015-04-02 20:45
I have never seen this error before. Have you successfully installed other python modules via pip?

**Comment by eebeer** [comment] 2015-04-02 20:46
I installed numpy, wheel via pip and I checked numpy and wheel work well.

**Comment by rhyolight** [comment] 2015-04-02 20:52
> `drwx------ 6 dkim451 ece 4.0K Apr 2 11:27 pip-4mnzsw-build`

This says that `root` has read/write/exe access to the `tmp` folder, but I think it should be universally writable. Try `sudo chmod 755 /tmp` and reinstall?

**Comment by eebeer** [comment] 2015-04-02 20:53
I don't have sudo, but I will contact admin. Thanks.

**Comment by rhyolight** [comment] 2015-04-06 23:06
@eebeer Any progress?

**Comment by eebeer** [comment] 2015-04-07 00:11
I figured it out pip install pkg --user does not work.

I am asking admin, and they are trying to diff. version of pip.

I will update asap.

Thank you.

sent from mobile

**Comment by rhyolight** [comment] 2015-04-10 15:46
@eebeer I think I'm going to close this because it seems that the problem is a permissions problem with the `/tmp` directory. We assume anyone installing NuPIC has xwr access to this directory. If you find that there is a different root problem, please feel free to re-open this ticket with more information. Thanks for the report, and best wishes.

**Closed by rhyolight** 2015-04-10 15:46 UTC
Labels: wat?
