### ISSUE TITLE
Clean up spatial pooler documentation

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#662] opened 2014-02-19 18:58 UTC
Many of the comments in `$NUPIC/py/nupic/research/spatial_pooler.py` are redundant with the comments in the C++ code in `nupic.core`. This task is to remove the redundant documentation from Python and include a link to the C++ file.   A couple of things to consider:

1) There are some small differences between the two implementations - we should document the Python differences in the Python class. For example, the method signatures might be slightly different in Python.

2) If there is documentation that is missing from the CPP file, then we should note it here and create an issue in nupic.core to address it.

This is a great newbie task for those who want to learn about the spatial pooler API.

Relates to the discussion here:  

http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2014-January/000152.html

**Comment by rhyolight** [comment] 2016-07-14 16:30
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

**Comment by subutai** [comment] 2016-07-14 21:20
@rhyolight I don't have a strong opinion on this anymore. 

The good thing about the current state is that the documentation is right there for a person looking at the python code. They don't have to go to another C++ repository and understand C++. (This issue was actually created when C++ and Python were in the same repository so it was a bit easier - now users have to go to a separate repository.)

The bad thing is that there is duplication, so we have to be careful to keep the two in sync.

**Comment by scottpurdy** [comment] 2016-07-14 21:27
I think the right way to handle this is to have the SP pseudocode in BAMI (or other public resource) and then the implementations can refer to that document for the algorithmic details but additionally have thorough documentation of the implementation (parameters, intended use and purpose, return values, etc for each function). There will still be some duplication of documentation but the important shared aspect (pseudocode and description) will be in just one place.

**Comment by subutai** [comment] 2016-07-14 21:33
@scottpurdy Isn't that the way it is now?  The issue here is that Python and C++ documentation is duplicated.

**Comment by scottpurdy** [comment] 2016-07-14 21:41
Yeah I think that is mostly how we do it now. I don't have a problem with the implementation documentation being duplicated since the logic is duplicated as well.

**Comment by subutai** [comment] 2016-07-14 21:42
OK, I vote to just close this issue then.

**Closed** 2016-07-14 21:59 UTC
Labels: newbie, subject:algorithms, type:cleanup, type:docs, under-review

**Comment by ywcui1990** [comment] 2016-07-14 22:55
@rhyolight @subutai  @scottpurdy Thanks for you all. I believe this is the first NuPIC issue I worked on. It's great to have it closed :)
