### ISSUE TITLE
Port TM changes from C++ to Python

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#3177] opened 2016-06-21 20:38 UTC
@mrcslws made some significant changes to the C++ TM here:
https://github.com/numenta/nupic.core/pull/917

The Python implementation should use similar logic.

**Comment by scottpurdy** [comment] 2016-06-21 20:39
@andrewmalta13

**Comment by rhyolight** [comment] 2016-06-22 14:41
This is a duplicate of https://github.com/numenta/nupic/issues/3116.

**Closed by rhyolight** 2016-06-22 14:41 UTC
