### ISSUE TITLE
Experiment with topology support in the TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#910] opened 2014-05-02 06:25 UTC
It might be possible to add topology support in the TP by simply modifying `chooseCellsToLearnFrom` to choose cells spatially close to the current one. Experiment with this approach.

**Comment by rhyolight** [comment] 2016-07-20 18:27
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Comment by subutai** [comment] 2016-07-21 22:51
I think this is fine, but I would change it to temporal_memory implementation rather than TP. It is also probably a research activity, not really something for the NuPIC repo.

**Comment by rhyolight** [comment] 2016-07-22 21:31
Replaced by https://github.com/numenta/nupic.research/issues/578.

**Closed by rhyolight** 2016-07-22 21:31 UTC
Labels: priority:4, subject:algorithms, under-review
