### ISSUE TITLE
unable to get predictedActiveCells output after enabling computePredictedActiveCellIndices

### ISSUE THREAD

**Issue by marionleborgne** [numenta/nupic#2405] opened 2015-08-10 21:13 UTC
I am using the `tm_py` implementation of the TM. I need to access the output `predictedActiveCells`. When I set the parameter `computePredictedActiveCellIndices` to `True` I get the following error:
 
```
Traceback (most recent call last):
  File "/Users/mleborgne/_git/nupic.research/classification/classify_sensor_data.py", line 191, in <module>
    run(network, NUM_RECORDS, PARTITIONS, _OUT_FILE)
  File "/Users/mleborgne/_git/nupic.research/classification/classify_sensor_data.py", line 93, in run
    net.run(1)
  File "/Users/mleborgne/_git/nupic/nupic/engine/__init__.py", line 667, in run
    engine.Network.run(self, n)
  File "/Users/mleborgne/_git/nupic/nupic/bindings/engine_internal.py", line 1146, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 464, in compute
    self._compute(inputs, outputs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 525, in _compute
    activeState = self._tfdr.getActiveState().reshape(-1).astype('float32')
AttributeError: 'TPShim' object has no attribute 'getActiveState'
```

**Comment by marionleborgne** [comment] 2015-08-10 21:19
@chetan51 FYI, this blocks https://github.com/numenta/nupic.research/pull/257. Thanks!

**Comment by chetan51** [comment] 2015-08-10 21:21
Duplicate of https://github.com/numenta/nupic/issues/2341.

**Closed by chetan51** 2015-08-10 21:21 UTC
