### ISSUE TITLE
Remove temporal pooling logic from TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#908] opened 2014-05-02 06:22 UTC
Since "pooling" is not actually being used anymore, let's remove the extra logic from the TP. We can also get rid of the idea of "sequence segments".

**Comment by breznak** [comment] 2015-02-23 06:56
ping? since 'pooling' seems to be part of TM now..?

**Comment by rhyolight** [comment] 2016-07-20 18:27
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Comment by subutai** [comment] 2016-07-20 20:38
> Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

I think you are right. I think this issue is obsolete and vote for closing it.

**Closed** 2016-07-20 21:16 UTC
Labels: subject:algorithms, type:cleanup, under-review
