### ISSUE TITLE
TP: Experiment with a different way to prevent oversampling from bursting columns

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#909] opened 2014-05-02 06:24 UTC
Currently, we have a separate inference state and learn state, and learn state only allows one predicted cell per column. Instead, it would be cleaner to combine them and modify `chooseCellsToLearnFrom` to sample at most one cell per column. Experiment with this approach, and see how it affects performance.

**Comment by rhyolight** [comment] 2016-07-20 18:27
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.

Specifically, this issue has to do with improvements to the TP algorithm, which seems to have been deprecated in favor of the TM algorithm.

**Comment by subutai** [comment] 2016-07-21 22:52
Obsolete - old TP algorithm. New one selects from winner cells which avoids this problem, I believe.

**Closed** 2016-07-22 00:48 UTC
Labels: subject:algorithms, under-review
